### ISSUE TITLE
Example in README does not work with current Rakudo (v2022.07)

### ISSUE THREAD

**Issue by markjreed** [FCO/ProblemSolver#3]
Attempting to run the SEND + MORE = MONEY example in the README results in this:

```
Too many positionals passed; expected 0 to 2 arguments but got 3
```

The problem line is the `return False if not func(|%values)` line in `run-constraints`:

 ```
method !run-constraints(%values, :$debug) {
	my @cons = self!get-constraints-for-vars(%values);
	for @cons -> &func {
		return False if not func(|%values) # <-- error happens here
	}
	True
}
```

And the constraint it's breaking on is this one:

```
$problem.constraint-vars: -> &:infix<!=>, <S E N D M O R Y>;
```

Perhaps it used to work, but currently `&:infix<!->` doesn't take an arbitrary number of arguments. Even `[!=]`, though, only compares its arguments pairwise, so it doesn't guarantee uniqueness. 

Replacing the constraint with this works, though there's probably a more efficient solution:

```
$problem.constraint-vars: -> *@_ { @_.unique == @_ }, <S E N D M O R Y>;
```

**Comment by FCO** [comment]
Thanks! I'll take a look at it as soon as possible.
